name: dope_path
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  share_plus: ^7.2.2
  url_launcher: ^6.0.9  
  webview_flutter: ^2.0.12
  http: ^0.13.3
  provider: ^5.0.0
  local_auth: ^2.2.0
  shared_preferences: ^2.0.0
  geolocator: ^8.0.1
  google_maps_flutter: ^2.0.8
  permission_handler: ^10.2.0
  location: ^5.0.3
  flutter_local_notifications: ^8.1.1+1
  table_calendar: ^3.0.8
  google_place: ^0.4.7
  timezone: ^0.8.0
  google_maps_webservice: ^0.0.19+1
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
